"""create market data tables"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7fe0b5c4acb3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "markets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("external_market_id", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("condition_id", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("resolution_rules", sa.Text(), nullable=True),
        sa.Column("resolution_source", sa.Text(), nullable=True),
        sa.Column("close_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepting_orders", sa.Boolean(), nullable=True),
        sa.Column("enable_order_book", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "external_market_id", name="uq_market_provider_external"),
    )
    op.create_index(op.f("ix_markets_status"), "markets", ["status"], unique=False)
    op.create_table(
        "market_outcomes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("market_id", sa.Uuid(), nullable=False),
        sa.Column("outcome_name", sa.Text(), nullable=False),
        sa.Column("token_id", sa.Text(), nullable=True),
        sa.Column("outcome_index", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("outcome_index >= 0", name="ck_outcome_index"),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market_id", "id", name="uq_outcome_market_id"),
        sa.UniqueConstraint("market_id", "outcome_index", name="uq_outcome_market_index"),
        sa.UniqueConstraint("market_id", "token_id", name="uq_outcome_market_token"),
    )
    op.create_table(
        "market_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("market_id", sa.Uuid(), nullable=False),
        sa.Column("outcome_id", sa.Uuid(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata_captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("best_bid", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("best_ask", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("midpoint", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("spread", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("last_trade_price", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("liquidity", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("volume", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("open_interest", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("minimum_order_size", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("tick_size", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("fee_rate", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("fees_enabled", sa.Boolean(), nullable=True),
        sa.Column("fee_exponent", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("fee_taker_only", sa.Boolean(), nullable=True),
        sa.Column("fee_rebate_rate", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("raw_payload_hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint("best_ask IS NULL OR best_ask BETWEEN 0 AND 1", name="ck_snapshot_ask"),
        sa.CheckConstraint("best_bid IS NULL OR best_bid BETWEEN 0 AND 1", name="ck_snapshot_bid"),
        sa.CheckConstraint("spread IS NULL OR spread >= 0", name="ck_snapshot_spread"),
        sa.ForeignKeyConstraint(
            ["market_id", "outcome_id"],
            ["market_outcomes.market_id", "market_outcomes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_snapshot_market_captured",
        "market_snapshots",
        ["market_id", "captured_at"],
        unique=False,
    )
    op.create_index(
        "ix_snapshot_outcome_captured",
        "market_snapshots",
        ["outcome_id", "captured_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_snapshot_outcome_captured", table_name="market_snapshots")
    op.drop_index("ix_snapshot_market_captured", table_name="market_snapshots")
    op.drop_table("market_snapshots")
    op.drop_table("market_outcomes")
    op.drop_index(op.f("ix_markets_status"), table_name="markets")
    op.drop_table("markets")
    # ### end Alembic commands ###
